on:
  workflow_dispatch:
  push:
    branches:
      - main

# Starts jobs and sets the type of runner (Windows) they will run on
jobs:
  build-and-deploy-to-dockerhub:
    runs-on: windows-latest

    steps:
    # Checks out repository so your workflow can access it
    - uses: actions/checkout@v1
    - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and Push container to registry
      run: |
        docker build -t ivanmarques/testwinimage:1 .
        docker push ivanmarques/testwinimage:1